### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by fregante** [bntzio/wipe-modules#1] opened 2017-05-06 01:52 UTC
<img width="877" alt="screen shot 2017-05-06 at 09 51 11" src="https://cloud.githubusercontent.com/assets/1402241/25768980/93ebb8f2-3241-11e7-978e-e3747b1cea56.png">

Those folders exist and many have node_modules

**Comment by furey** [comment] 2017-05-06 02:08
I had the same problem – had to patch `wipe-modules.sh` with…

```bash
# …
for d in `find . -maxdepth 1 -type d -mtime +$last_modified`; do
    if [ "$d" == "." ]; then
      continue
    fi
    # move to code dir subdirectory
    # …
```

I'll submit a PR.

**Comment by furey** [comment] 2017-05-06 02:20
PR submitted (https://github.com/bntzio/wipe-modules/pull/2). 👍🏻

**Comment by bntzio** [comment] 2017-05-06 03:54
@bfred-it @furey did that worked for you? I think the problem is with folders with a space in their name, that causes the program to `cd` and get lost in the loop (causing the no such file or directory issue).

Let's say you have a folder named `my playground`.
The program will `cd` in my (causing the issue), and breaking the execution.

I'm trying to fix that, in the meanwhile, this works if you have non-space folder names.

**Comment by furey** [comment] 2017-05-06 05:05
Hi @bntzio,

At my end, the "." problem and "folders with a space in their name" (I didn't test against whitespaced directory names originally but have now) were both issues, which I've now patched on #2. 👍🏻

Cheers.

**Comment by bntzio** [comment] 2017-05-08 03:26
Closing due 👉 #2 and https://github.com/bntzio/wipe-modules/commit/df9b1e5be6c370ba16c6a790c713f9467cf5a002

**Closed as completed by bntzio** 2017-05-08 03:26 UTC

**Comment by geowarin** [comment] 2017-05-09 09:14
Hello, thanks for this module.
I still have the problem mentioned in this issue in 1.1.0.

![bug](http://i.imgur.com/FwL77zU.png)

**Comment by bntzio** [comment] 2017-05-09 09:17
@geowarin please use the absolute path to the directory where your code projects live.

Example: `~/Desktop/code-projects`

**Comment by bntzio** [comment] 2017-05-09 09:40
Mm... that's strange, I got the same error, then moved out the first directory mentioned on the error logs (in your case it would be `00-PRES`) then executed the script until I get it to work with the `--dry` flag to see what may be removed, once it's working I moved the folder back, ran the script and everything went fine again 🤔

It works even with the `.` as the path.

**Comment by bntzio** [comment] 2017-05-09 10:38
Ok, I found the issue, will commit the fix in a few hours 😄 thanks for pointing this out! @geowarin

**Comment by bntzio** [comment] 2017-05-09 20:50
@geowarin here's it is c4993fceec59b89a1318b8f8cb4a1ec660175532 😄

Could you please upgrade to the newest version `v.1.1.1` and then try again?

**Comment by geowarin** [comment] 2017-05-09 22:34
Totally works! 👍
Thank you so much :smile:
